# Generated by Django 5.2 on 2026-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
