# Generated by Django 5.2 on 2026-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Profile/default/images.jpg', null=True, upload_to='Profile/users'),
        ),
    ]
