# Generated by Django 5.2 on 2026-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
