# Generated by Django 5.2 on 2026-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewmodel_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
