# Generated by Django 5.2 on 2026-06-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewmodel_updated_date'),
        ('shop', '0008_productmodel_avg_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='shop.productmodel'),
        ),
    ]
