# Generated by Django 5.2 on 2026-05-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='breif_description',
            new_name='brief_description',
        ),
    ]
