# Generated by Django 5.2 on 2026-05-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_breif_description_productmodel_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
