# Generated by Django 5.2 on 2026-06-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productmodel_avg_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='avg_review',
            new_name='avg_rate',
        ),
    ]
