# Generated by Django 5.2 on 2026-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_avg_review_productmodel_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
