# Generated by Django 5.2 on 2026-05-13 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='expier_date',
            new_name='expiering_date',
        ),
        migrations.RenameField(
            model_name='couponmodel',
            old_name='max_limit',
            new_name='max_limit_usage',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'لغو شده')], default=1),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
