# Generated by Django 5.2 on 2026-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_expier_date_couponmodel_expiering_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='coupon',
            new_name='code',
        ),
    ]
