# Generated by Django 5.2 on 2026-05-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_coupon_couponmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.couponmodel'),
        ),
    ]
