# Generated by Django 5.2 on 2026-05-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.couponmodel'),
        ),
    ]
