# Generated by Django 5.2 on 2026-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
