# Generated by Django 5.2 on 2026-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_couponmodel_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='active',
        ),
    ]
