# Generated by Django 5.2 on 2026-05-20 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_couponmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 20, 21, 49, 51, 329532, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
