# Generated by Django 5.2 on 2026-05-22 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_couponmodel_expiering_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 22, 14, 56, 2, 42330, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
