# Generated by Django 5.2 on 2026-05-22 15:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_couponmodel_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmodel'),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 22, 15, 1, 9, 953638, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
