# Generated by Django 5.2 on 2026-06-01 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_ordermodel_payment_alter_couponmodel_expiering_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 1, 8, 21, 31, 837323, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
