# Generated by Django 5.2 on 2026-06-03 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 3, 20, 44, 34, 136726, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
