# Generated by Django 5.2 on 2026-06-12 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_couponmodel_expiering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 12, 9, 58, 55, 977981, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
