# Generated by Django 5.2 on 2026-06-13 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_couponmodel_expiering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiering_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 13, 19, 6, 6, 509991, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
